export enum PluginSettings {
    ApplicationSearch = "Application Search",
    Shortcuts = "Shortcuts",
    Translation = "Translation",
    WebSearch = "Websearch",
    FileBrowser = "File Browser",
    OperatingSystemCommands = "Operating System Commands",
    OperatingSystemSettings = "Operating System Settings",
    Calculator = "Calculator",
    Url = "Url",
    MTG = "Mtg",
    Email = "Email",
    CurrencyConverter = "Currency Converter",
    Workflow = "Workflow",
    Commandline = "Commandline",
    SimpleFolderSearch = "Simple Folder Search",
    ColorConverter = "Color Converter",
    BrowserBookmarks = "Browser Bookmarks",
    Dictionary = "Dictionary",
}
